T4 actuators and T4 AOA now usable in Paparazzi master (#3401)
* T4 actuators and T4 AOA now usable in Paparazzi master

* Rename ACTUATORS_T4_UART_DEV to ACTUATORS_T4_UART_PORT

since build failure on semaphore test  gave:
modules/actuators/actuators_t4_uart.c:194:19: error: ‘ACTUATORS_T4_PORT’ undeclared

* Rename ACTUATORS_T4_UART_PORT to ACTUATORS_T4_PORT

Wrongly named, FYI since for the future plans port could be as well CAN or I2C type no specific reference to UART device just plain ACTUATORS_T4_PORT